#!/usr/bin/env php
<?php

use Illuminate\Container\Container;
use Symfony\Component\Console\Application;
use NtimYeboah\Command\SeedDatabaseCommand;

require __DIR__ . '/vendor/autoload.php';
$dotenv = new \Dotenv\Dotenv(__DIR__);
$dotenv->load();

$container = Container::getInstance();

$application = new Application('Database Seed Command');
$application->add($container->make(SeedDatabaseCommand::class));

$application->run();

